
// default
//#define MUMAN_MESSAGE_STRING 1 
//#define MUMAN_MESSAGE_INT 2


#define WOO_MESSAGE_GET 1
#define WOO_MESSAGE 2
#define WOO_MESSAGE_OK 3

#define ECHO_MESSAGE 65534
#define BLANK_MESSAGE 65535

